"""Static type hints for the Rust extension.

The implementation is generated by PyO3; this stub lets type checkers
treat ``veloforge._core`` as a typed module. Keep names in sync with
``crates/veloforge-py/src/lib.rs``.
"""

from __future__ import annotations

from typing import List

class SensorEngine:
    def __init__(self) -> None: ...
    def feed(self, chunk: bytes) -> List[Sample]: ...
    def state(self) -> StateView: ...
    def reset(self) -> None: ...

class DeviceInfo:
    id: str
    name: str

class Sample:
    monotonic_ns: int
    linear_accel: List[float]
    velocity: List[float]
    bar_velocity_mps: float
    stationary: bool
    phase: str
    quality: int

class StateView:
    frames_decoded: int
    bad_prefixes: int
    velocity: List[float]
    bar_velocity_mps: float
    stationary: bool
    phase: str
    quality: int

__version__: str

def encode_command(name: str) -> List[int]: ...
